
import React from 'react';
import { User as FirebaseUserType } from 'firebase/auth'; // Import Firebase's User type
export type FirebaseUser = FirebaseUserType;

export type Page = 'Dashboard' | 'Cameras' | 'Analytics' | 'Reports';

export type CameraStatus = 'Online' | 'Offline' | 'Recording';

export interface Analytic {
  id: string; // Changed to string for Firestore document ID
  name: string;
  description: string;
  version: string;
  iconName: string; // Store icon name (string) for Firebase
  icon?: React.FC<{className?: string}>; // Optional: frontend-only property after mapping
  tags: string[];
}

export interface Camera {
  id: string; // Changed to string for Firestore document ID
  name: string;
  location: string;
  ipAddress: string;
  status: CameraStatus;
  videoUrl: string; 
  analyticIds: string[]; // Changed to string[] for Firestore document IDs
}


export type EventSeverity = 'Low' | 'Medium' | 'High' | 'Critical';

export interface ReportEvent {
  id: string; // Changed to string for Firestore document ID
  timestamp: string;
  cameraName: string;
  analyticName: string;
  severity: EventSeverity;
  videoUrl: string; 
  details: string;
}

export interface AddCameraModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (camera: Omit<Camera, 'id' | 'status' | 'videoUrl' | 'analyticIds'> | Camera) => Promise<void>;
  cameraToEdit: Camera | null;
}

export interface ApplyAnalyticsModalProps {
    isOpen: boolean;
    onClose: () => void;
    analytic: Analytic | null;
    cameras: Camera[];
    onSave: (analyticId: string, cameraIds: string[]) => Promise<void>; // Analytic/camera IDs are strings
}

export interface EventDetailModalProps {
    isOpen: boolean;
    onClose: () => void;
    event: ReportEvent | null;
}

export interface LivePreviewModalProps {
    isOpen: boolean;
    onClose: () => void;
    camera: Camera | null;
}

// New types for video analysis (used by AnalyzeVideoModal and LiveAnalyticsModal)
export interface VideoAnalysisResult {
    frameNumber: number;
    timestamp: number; // in seconds
    imageUrl: string; // Base64 image data for the frame
    description: string; // Text description from Gemini
}

export interface AnalyzeVideoModalProps {
    isOpen: boolean;
    onClose: () => void;
}

// New type for API Test Modal
export interface ApiTestModalProps {
    isOpen: boolean;
    onClose: () => void;
}

// New type for Live Analytics Modal
export interface LiveAnalyticsModalProps {
  isOpen: boolean;
  onClose: () => void;
  camera: Camera | null;
  onAddEvent: (event: Omit<ReportEvent, 'id'>) => Promise<void>; // Event ID is generated by Firestore
  analytics: Analytic[]; // Pass analytics as prop
}